import createClient, { type Middleware } from 'openapi-fetch'
import type { paths } from './schema' // generated by openapi-typescript

const authMiddleware: Middleware = {
  onRequest({ request, options }) {
    const accessToken = localStorage.getItem('music-fun-access-token')
    if (accessToken) {
      request.headers.set('Authorization', 'Bearer' + accessToken)
    }
    return request
  },
  onResponse({ response }) {
    if (!response.ok) {
      // Will produce error messages like "https://example.org/api/v1/example: 404 Not Found".
      throw new Error(`${response.url}: ${response.status} ${response.statusText}`)
    }
  }
}

export const client = createClient<paths>({
  baseUrl: 'https://musicfun.it-incubator.app/api/1.0/',
  headers: {
    // TODO удалить этот ключ!
    'api-key': 'e42851f7-0d43-4cb2-8e28-b95e07d14719'
  }
})
client.use(authMiddleware)
