import createClient from 'openapi-fetch'
import type { paths } from './schema' // generated by openapi-typescript

export const client = createClient<paths>({
  baseUrl: 'https://musicfun.it-incubator.app/api/1.0/',
  headers: {
    // TODO удалить этот ключ!
    'api-key': '8ca9f37a-81c3-44d3-b627-0a28713999e7',
  },
})
